inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/MethodLength:
  Max: 12

AllCops:
  Include:
    - '**/Deployfile'
    - '**/Runfile'
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'