version: "3.3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - files_internal

  app:
    image: nextcloud:20
    restart: always
    labels:
      - traefik.backend=files-master
      - traefik.frontend.rule=Host:files.stiftungswo.ch
      - traefik.frontend.passHostHeader:"true"
      - traefik.docker.network=traefik
    volumes:
      - ./html:/var/www/html
    networks:
      - files_internal
      - traefik

      
networks:
  traefik:
    external: true
  files_internal:
    external: false
