version: "3.7"
networks:
 traefik:
    external: true
services:
  traefik:
    image: traefik:v1.7.12
    ports:
      - "8080:80"
      - "4433:443"
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
    networks:
      - traefik
    labels:
      traefik.frontend.rule: "Host:traefik.stiftungswo.ch"
    restart: unless-stopped
