[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.websecure]
  address = ":443"

[api]
  insecure = true
  dashboard = true

[providers.docker]
  network = "traefik"
  exposedByDefault = false

[acme]
  email = "office@stiftungswo.ch"
  storage = "acme.json"
  entryPoint = "websecure"
  onHostRule = true
  [acme.tlsChallenge]
