version: "3.3"
networks:
  traefik:
    external: true
  internal:
    external: false
services:
  frontend:
    image: nginx:alpine
    labels:
      - "traefik.backend=lime-master"
      - "traefik.frontend.rule=Host:survey.stiftungswo.ch"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
    depends_on:
      - limesurvey
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - lime:/var/www/html
    networks:
      - internal
      - traefik
    restart: unless-stopped
  limesurvey:
    image: martialblog/limesurvey:fpm-alpine
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - /var/www/vhosts/stiftungswo.ch/deploy/limesurvey/master.env
    volumes:
      - ./plugins:/var/www/html/plugins
      - lime:/var/www/html
volumes:
  lime:
