version: "3.3"

networks:
  traefik:
    external: true
  survey_internal:
    external: false

services:
  frontend:
    image: nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.limesurvey-master.rule=Host(`survey.stiftungswo.ch`)
      - traefik.http.services.limesurvey-master.loadbalancer.passhostheader=true
    depends_on:
      - limesurvey
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - lime:/var/www/html
    networks:
      - survey_internal
      - traefik
    restart: unless-stopped

  limesurvey:
    image: martialblog/limesurvey:fpm-alpine
    labels:
      - "traefik.enable=false"
    networks:
      - survey_internal
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - lime:/var/www/html
      - ./plugins:/var/www/html/plugins
volumes:
  lime:
